/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_toocol_ssh_common_jni_TerminatioJNI */

#ifndef _Included_com_toocol_ssh_common_jni_TerminatioJNI
#define _Included_com_toocol_ssh_common_jni_TerminatioJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_toocol_ssh_common_jni_TerminatioJNI
 * Method:    getCh
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_toocol_ssh_common_jni_TerminatioJNI_getCh
  (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TerminatioJNI
 * Method:    chooseFiles
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_toocol_ssh_common_jni_TerminatioJNI_chooseFiles
  (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TerminatioJNI
 * Method:    chooseDirectory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_toocol_ssh_common_jni_TerminatioJNI_chooseDirectory
  (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TerminatioJNI
 * Method:    getWindowWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_toocol_ssh_common_jni_TerminatioJNI_getWindowWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TerminatioJNI
 * Method:    getWindowHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_toocol_ssh_common_jni_TerminatioJNI_getWindowHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TerminatioJNI
 * Method:    getCursorPosition
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_toocol_ssh_common_jni_TerminatioJNI_getCursorPosition
  (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TerminatioJNI
 * Method:    setCursorPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_toocol_ssh_common_jni_TerminatioJNI_setCursorPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_toocol_ssh_common_jni_TerminatioJNI
 * Method:    cursorBackLine
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_toocol_ssh_common_jni_TerminatioJNI_cursorBackLine
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_toocol_ssh_common_jni_TerminatioJNI
 * Method:    showCursor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_toocol_ssh_common_jni_TerminatioJNI_showCursor
  (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TerminatioJNI
 * Method:    hideCursor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_toocol_ssh_common_jni_TerminatioJNI_hideCursor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
